#!/usr/bin/env node
/**
 * Supabase schema sync script
 *
 * Workflow:
 * 1. Edit declarative schema files in supabase/database/*.sql
 * 2. Run `pnpm db:sync` to diff and apply changes locally
 * 3. Run `pnpm db:push` to push synced migrations to the linked remote project
 * 4. Run `pnpm db:types` to regenerate TypeScript types
 */

import { spawnSync } from 'node:child_process'
import { existsSync, writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')
const SUPABASE_DIR = join(ROOT, 'supabase')
const DATABASE_DIR = join(SUPABASE_DIR, 'database')
const TYPES_OUTPUT = join(ROOT, 'packages/shared-types/src/database.types.ts')

const command = process.argv[2] ?? 'sync'

function log(message) {
  console.log(`[supabase-sync] ${message}`)
}

function fail(message, code = 1) {
  console.error(`[supabase-sync] ERROR: ${message}`)
  process.exit(code)
}

function run(cmd, args, options = {}) {
  log(`Running: ${cmd} ${args.join(' ')}`)
  const result = spawnSync(cmd, args, {
    cwd: ROOT,
    stdio: 'inherit',
    shell: process.platform === 'win32',
    ...options,
  })
  if (result.status !== 0) {
    fail(`Command failed: ${cmd} ${args.join(' ')}`, result.status ?? 1)
  }
}

function ensureSupabaseCli() {
  const result = spawnSync('supabase', ['--version'], {
    cwd: ROOT,
    stdio: 'pipe',
    shell: process.platform === 'win32',
  })
  if (result.status !== 0) {
    fail(
      'Supabase CLI is not installed. Install it from https://supabase.com/docs/guides/cli/getting-started',
    )
  }
  log(`Using ${result.stdout.toString().trim()}`)
}

function ensureSchemaFiles() {
  if (!existsSync(DATABASE_DIR)) {
    fail(`Schema directory not found: ${DATABASE_DIR}`)
  }
  const schemaFiles = [
    '00_extensions.sql',
    '10_public_profiles.sql',
    '20_public_ai_logs.sql',
    '30_stripe_billing.sql',
    '40_rls_policies.sql',
  ]
  for (const file of schemaFiles) {
    if (!existsSync(join(DATABASE_DIR, file))) {
      fail(`Missing schema file: supabase/database/${file}`)
    }
  }
  log('Declarative schema files verified.')
}

function timestamp() {
  const now = new Date()
  const pad = (n) => String(n).padStart(2, '0')
  return `${now.getFullYear()}${pad(now.getMonth() + 1)}${pad(now.getDate())}${pad(now.getHours())}${pad(now.getMinutes())}${pad(now.getSeconds())}`
}

function sync() {
  ensureSchemaFiles()
  const migrationName = `sync_${timestamp()}`
  log('Generating migration diff from declarative schema files...')
  run('supabase', ['db', 'diff', '-f', migrationName, '--local'])
  log('Applying migrations to local database...')
  run('supabase', ['migration', 'up', '--local'])
  log('Local sync complete. Review generated migration in supabase/migrations/.')
}

function push() {
  ensureSchemaFiles()
  log('Pushing migrations to linked remote Supabase project...')
  run('supabase', ['db', 'push'])
  log('Remote push complete.')
}

function pull() {
  log('Pulling remote schema into local migrations (drift recovery only)...')
  run('supabase', ['db', 'pull'])
  log('Pull complete. Commit the generated migration if changes were captured.')
}

function diff() {
  ensureSchemaFiles()
  const migrationName = `diff_${timestamp()}`
  log('Generating diff without applying...')
  run('supabase', ['db', 'diff', '-f', migrationName, '--local'])
  log('Diff generated. Check supabase/migrations/ for the new file.')
}

function types() {
  log('Generating TypeScript types from Supabase schema...')
  const result = spawnSync(
    'supabase',
    ['gen', 'types', 'typescript', '--local', '--schema', 'public,stripe'],
    {
      cwd: ROOT,
      stdio: 'pipe',
      shell: process.platform === 'win32',
    },
  )

  if (result.status !== 0) {
    log('Local type generation failed. Trying linked project...')
    run('supabase', [
      'gen',
      'types',
      'typescript',
      '--linked',
      '--schema',
      'public,stripe',
      '-o',
      TYPES_OUTPUT,
    ])
  } else {
    mkdirSync(dirname(TYPES_OUTPUT), { recursive: true })
    const header = `// Auto-generated by pnpm db:types — do not edit manually.\n\n`
    writeFileSync(TYPES_OUTPUT, header + result.stdout.toString())
    log(`Types written to ${TYPES_OUTPUT}`)
  }
}

function main() {
  ensureSupabaseCli()

  switch (command) {
    case 'sync':
      sync()
      break
    case 'push':
      push()
      break
    case 'pull':
      pull()
      break
    case 'diff':
      diff()
      break
    case 'types':
      types()
      break
    default:
      fail(`Unknown command: ${command}. Use sync | push | pull | diff | types`)
  }
}

main()
